version: "3.8"

services:
  fastapi:
    build:
      context: .
      dockerfile: Dockerfile.prod
    container_name: simulation_api
    env_file:
      - .env
    restart: always
    expose:
      - 8000
    depends_on:
      - nginx

  nginx:
    image: nginx:alpine
    container_name: nginx_proxy
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - fastapi
